name: onboarding_flow
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper : any
  firebase_auth: any
  # flutter_facebook_login: ^1.1.1
  shared_preferences: any
  cloud_firestore: ^0.13.6
  intl: any
  carousel_slider: ^1.3.0
  sliding_up_panel: any
  cached_network_image: any
  smooth_page_indicator: any
  # fit_kit: ^1.1.1
  audioplayers: any
  video_player: ^0.10.8+1
  mailer: ^3.0.3
  table_calendar: ^2.2.2
  dropdownfield: ^1.0.3
  firebase_database: ^3.1.6
  # firebase_admob: ^0.6.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/music/
    - assets/images/default.png
    - assets/images/preview.jpg
    - assets/images/logo.png
    - assets/images/getlimber.png
    - assets/images/soccerbasics.png
    - assets/images/thecore.png
    - assets/images/narscar.png
    - assets/images/ball.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: HK Grotesk
      fonts:
        - asset: assets/fonts/hk-grotesk.bold.ttf
    - family: Xbka
      fonts:
        - asset: assets/fonts/Xbka.otf
    - family: Comic
      fonts:
        - asset: assets/fonts/COMIC.TTF
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
